package-name := yandex-maps-sat-tileindex
PKG := $(package-name)
SRCPKG := yandex-maps-sat-tileindex
$(package-name): DESC = Sample package
$(package-name): FILES = \
    /var/lib/yandex/maps/sample/data:data\

include /usr/share/yandex/maps/build/build.mk
