package-name := yandex-maps-swagger
SRCPKG = $(package-name)
PKG = $(package-name)

USE += backport

URL = https://codeload.github.com/swagger-api/swagger-ui/tar.gz/v2.1.1-M1
MD5SUM = 69205ddcecb4efad4f0737198bbc0a49
PATCHES = custom_default_url.patch

include /usr/share/yandex/maps/build/build.mk

bp_tarball = v2.1.1-M1.tar.gz

bp-default-configure:;
bp-default-build:;
bp-default-install:;
