package-name := libyandex-maps-pkostikov-sample

PKG := $(package-name)
SRCPKG := $(package-name)

BUILD_DEPENDS = \
    python-gdal (=1.8.0-2~yandex1) \
    libgeos-dev (=3.2.2-3.yandex) \


include /usr/share/yandex/maps/build/build.mk
