package-name := libyandex-maps-pkostikov-sample

PKG := $(package-name)
SRCPKG := $(package-name)

BUILD_DEPENDS = \
    gdal-bin (=1.8.0-2~yandex1) \
    gcc-4.4 (>= 4.4.3-4ubuntu5.1) \


include /usr/share/yandex/maps/build/build.mk
