BIN := sample 

sample: SRCS = \
    sample.cpp

sample: INCLUDES += \
    /usr/include/ImageMagick

sample: LIBS = \
    Magick++ \

CXX = g++-4.6
CXXFLAGS += -std=c++0x

include /usr/share/yandex/maps/build/build.mk